

# In[1]:


import smtplib
from email.message import EmailMessage 
import datetime
import pywhatkit
import requests
from geopy.geocoders import Nominatim

# In[37]:


def eas():
    
#   -----LOCATION COORDINATES AND ADDRESS FINDING

    #calling location service ip request to get coordinates - also gives other location information
    response_geo = requests.post("http://ip-api.com/json/43.242.229.220").json()
    print(response_geo)
    
    # calling the nominatim tool
    geoLoc = Nominatim(user_agent="GetLoc")

    # passing the coordinates
    locname = geoLoc.reverse(f"{response_geo['lat']}, {response_geo['lon']}")
    #print('locname: ',locname)
    
    
    
#   -----EMAIL ALERT SYSTEM-----
    msg=EmailMessage()
    msg.set_content(f'Hi, This is an autogenerated alert message from driver. Emergency has been detected. Please contact them. \n LOCATION: {locname.address}' )
    msg['subject']='Emergency alert request from Driver'
    recipients = ['pai.amogh@gmail.com', 'mrunmayee.m@somaiya.edu', 'navya.jain@somaiya.edu']
    msg['to']= ", ".join(recipients)
               
                   
    user="amo.nav.mrun@gmail.com"
    msg['from']= user
    password="bbspkidakcdxtgpo"
    server= smtplib.SMTP("smtp.gmail.com",587)
    server.starttls()
    server.login(user,password)
    server.send_message(msg)
    server.quit()
    
    
#     -----SMS ALERT SYSTEM------------
    message= f'Hi, This is an autogenerated alert message from driver. Emergency has been detected. Please contact them. \n LOCATION: {locname.address}'
    numbers = '9769309839,9987708622'

    url = "https://www.fast2sms.com/dev/bulkV2"

    payload= f'sender_id-TXTIND&message={message}&route=q&language=english&numbers={numbers}'

    headers = {
        'authorization': "AuRoS2EdYwO9HyUnXPLjF4lbp0k8zcBa7CJvIrefQTt6Ki1DMsDk36OZlxELepVRtGrywnMsu1dI58XP",
        'Content-Type': "application/x-www-form-urlencoded",
        'Cache-Control': "no-cache",
        }

#    response = requests.request("POST", url, data=payload, headers=headers)
    #print(response.text)
    
    
#     -----Whatsapp message ---
    current_time = datetime.datetime.now()
    pywhatkit.sendwhatmsg("+919769309839",f'Hi Amogh, This is an autogenerated alert message from driver. Emergency has been detected. Please contact them. \n LOCATION: {locname.address}',
                          current_time.hour,
                          current_time.minute+1)
    pywhatkit.sendwhatmsg("+919987708622",f'Hi Mrunmayee, This is an autogenerated alert message from driver. Emergency has been detected. Please contact them. \n LOCATION: {locname.address}',
                          current_time.hour,
                          current_time.minute+2)
           


# In[ ]:
# In[39]:


if __name__ == '__main__':
    eas()
    





# %%
